[package]
name = "builder_pattern_derive"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "3"
proc-macro2 = "1"
quote = "1"
syn = { version = "3", features = ["full", "visit"] }

[dev-dependencies]
builder-support = { package = "builder_pattern", path = "../builder_pattern" }
trybuild = "1"
